
export const professionals = [
  {
    _id:1,
    fullName: 'master',
    phone: '4545454545',
    field: 'plumber',
    address: 'somewhere in Delhi',
    rating: 5,
    profilePhoto : 'https://i.imgur.com/1bX5QH6.png',
  },
  {
    _id:2,
    fullName: 'dummy1',
    phone: '7897897897',
    field: 'painter',
    address: '1-123 pivot street, Porbandar',
    rating: 5,
    profilePhoto: 'https://i.pravatar.cc/150?img=3',
  },
  {
    _id:3,
    fullName: 'dummy2',
    phone: '7897897897',
    field: 'painter',
    address: '1-123 pivot street, Porbandar',
    rating: 5,
    profilePhoto: 'https://i.pravatar.cc/150?img=4',
  },
  {
    _id:4,
    fullName: 'dummy3',
    phone: '9999999999',
    field: 'electrician',
    address: 'Gandhinagar, Gujarat',
    rating: 4,
    profilePhoto: 'https://i.pravatar.cc/150?img=5',
  },
   {
      _id:5,
      fullName: 'Ramesh Plumber',
      phone: '9876543210',
      field: 'Plumber',
      address: 'Sector 10, Noida',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=10',
    },
    {
      _id:6,
      fullName: 'Anil Pipes',
      phone: '9871234560',
      field: 'Plumber',
      address: 'Gurgaon, Haryana',
      rating: 4,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=11',
    },
    {
      _id:7,
      fullName: 'Anil Pipes',
      phone: '9871234560',
      field: 'Plumber',
      address: 'Gurgaon, Haryana',
      rating: 4,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=11',
    },
    {
      _id:8,
      fullName: 'Anil Pipes',
      phone: '9871234560',
      field: 'Plumber',
      address: 'Gurgaon, Haryana',
      rating: 4,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=11',
    },
    {
      _id:9,
      fullName: 'Vikas Electrician',
      phone: '9898989898',
      field: 'Electrician',
      address: 'Saket, Delhi',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=6',
    },
    {
      _id:10,
      fullName: 'Manoj Volt',
      phone: '9123456780',
      field: 'Electrician',
      address: 'Dwarka, Delhi',
      rating: 4,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=7',
    },
    {
      _id:11,
      fullName: 'Manoj Volt',
      phone: '9123456780',
      field: 'Electrician',
      address: 'Dwarka, Delhi',
      rating: 4,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=7',
    },
    {
      _id:12,
      fullName: 'Manoj Volt',
      phone: '9123456780',
      field: 'Electrician',
      address: 'Dwarka, Delhi',
      rating: 4,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=7',
    },
  
    {
      _id:13,
      fullName: 'Deep Clean Pro',
      phone: '9009009001',
      field: 'Cleaner',
      address: 'Vashi, Navi Mumbai',
      rating: 4,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=8',
    },
    {
      _id:14,
      fullName: 'Sparkle Crew',
      phone: '9888777666',
      field: 'Cleaner',
      address: 'Rajkot, Gujarat',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=9',
    },
    {
      _id:15,
      fullName: 'Sparkle Crew',
      phone: '9888777666',
      field: 'Cleaner',
      address: 'Rajkot, Gujarat',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=9',
    },
    {
      _id:16,
      fullName: 'Sparkle Crew',
      phone: '9888777666',
      field: 'Cleaner',
      address: 'Rajkot, Gujarat',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=9',
    },
    {
      _id:17,
      fullName: 'Relax Spa',
      phone: '9870007890',
      field: 'Massage Therapist',
      address: 'Kolkata, West Bengal',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=12',
    },
    {
      _id:18,
      fullName: 'Heal & Relax',
      phone: '9100009990',
      field: 'Massage Therapist',
      address: 'Bandra, Mumbai',
      rating: 4,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=13',
    },
    {
      _id:19,
      fullName: 'Heal & Relax',
      phone: '9100009990',
      field: 'Massage Therapist',
      address: 'Bandra, Mumbai',
      rating: 4,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=13',
    },
    {
      _id:20,
      fullName: 'Heal & Relax',
      phone: '9100009990',
      field: 'Massage Therapist',
      address: 'Bandra, Mumbai',
      rating: 4,
      profilePhoto: 'https://i.pravatar.cc/150?img=13',
    },
    {
      _id:21,
      fullName: 'Ramesh Plumber',
      phone: '9876543210',
      field: 'Plumber',
      address: 'Sector 10, Noida',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=10',
    },
    {
      _id:22,
      fullName: 'Ramesh Plumber',
      phone: '9876543210',
      field: 'Plumber',
      address: 'Sector 10, Noida',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=10',
    },
    {
      _id:23,
      fullName: 'Ramesh Plumber',
      phone: '9876543210',
      field: 'Plumber',
      address: 'Sector 10, Noida',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=10',
    },
    {
      _id:24,
      fullName: 'Ramesh Plumber',
      phone: '9876543210',
      field: 'Plumber',
      address: 'Sector 10, Noida',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=10',
    },
    {
      _id:25,
      fullName: 'Ramesh Plumber',
      phone: '9876543210',
      field: 'Plumber',
      address: 'Sector 10, Noida',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=10',
    },
    {
      _id:26,
      fullName: 'Ramesh Plumber',
      phone: '9876543210',
      field: 'Plumber',
      address: 'Sector 10, Noida',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=10',
    },
    {
      _id:27,
      fullName: 'Ramesh Plumber',
      phone: '9876543210',
      field: 'Plumber',
      address: 'Sector 10, Noida',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=10',
    },
    {
      _id:28,
      fullName: 'Ramesh Plumber',
      phone: '9876543210',
      field: 'Plumber',
      address: 'Sector 10, Noida',
      rating: 5,
      profilePhoto: 'https://i.pravatar.cc/150?profilePhoto=10',
    },
];