// src/assets/allProjects.js
import img1 from "../assests/img4.png";
import img2 from "../assests/img5.png";
import img6 from "../assests/img6.png";
import img7 from "../assests/img7.png";
import img8 from "../assests/img8.png";
import img9 from "../assests/img9.png";
import img3 from "../assests/img1.png";
const allProjects = [
  {
    name: "Analog Clock",
    description: "A modern, animated analog clock with a Rolex-inspired design featuring and a stylish gradient background for an elegant and responsive look.",
    tech: ["HTML", "CSS", "JavaScript"],
    image: img9,
    github: "https://github.com/Himanshu250625/ClockBasic",
    live: "https://analog-clock-himanshu-singh.netlify.app/",
    category: "frontend",
  },
  {
    name: "Note App",
    description: "A simple note app using html, css and js A minimal and elegant Note App. Easily add or remove notes with a simple click and fully responsive layout..",
    tech: ["HTML", "CSS", "JavaScript"],
    image: img2,
    github: "https://github.com/Himanshu250625/note-app",
    live: "https://modernnoteappbyhim.netlify.app/",
    category: "frontend",
  },
  // Frontend Projects
  {
    name: "🔍 Image Explorer",
    description: "A image search app using html, css and js with responsive UI and Searching functionalty and download image feature.",
    tech: ["HTML", "CSS","JavaScript"],
    image: img7,
    github: "https://github.com/Himanshu250625/ImageSearchApp",
    live: "https://image-seach-appbyhim.netlify.app/",
    category: "frontend",
  },
  {
    name: "Password generator",
    description: "Generate secure passwords with options and copy paste button.",
    tech: ["React", "Tailwind",],
    image: img1,
    github: "https://github.com/Himanshu250625/PasswordGeneratorApp",
    live: "https://cozy-bonbon-9705fd.netlify.app/",
    category: "frontend",
  },
  {
    name: "Weather App🌦️",
    description: "A beautiful weather app using ReactJs and TailWind CSS which showing seating area temperature.",
    tech: ["React", "Tailwind"],
    image: img6,
    github: "https://github.com/Himanshu250625/WeatherApp",
    live: "https://weather-app-byhim.netlify.app/",
    category: "frontend",
  },
  {
    name: "DSA Tracker App",
    description: "A DSA problem tracker app using ReactJs, MaterialUI and Tailwind CSS.",
    tech: ["React", "MaterialUI", "Tailwind"],
    image: img8,
    github: "https://github.com/Himanshu250625/LeetCode_Problem_tracker_App",
    live: "https://leet-code-problem-tracker-app.vercel.app/",
    category: "frontend",
  },
  {
    name: "ToDo App",
    description: "Simple task manager with local storage.",
    tech: ["React", "Tailwind"],
    image: "/projects/todo.png",
    github: "#",
    live: "#",
    category: "frontend",
  },

  // Backend Projects
  {
    name: "Course API",
    description: "RESTful API for course management.",
    tech: ["Node.js", "MongoDB", "Express"],
    image: "/projects/backend-api.png",
    github: "#",
    live: "#",
    category: "backend",
  },
  {
    name: "Course API",
    description: "RESTful API for course management.",
    tech: ["Node.js", "MongoDB", "Express"],
    image: "/projects/backend-api.png",
    github: "#",
    live: "#",
    category: "backend",
  },
  {
    name: "Course API",
    description: "RESTful API for course management.",
    tech: ["Node.js", "MongoDB", "Express"],
    image: "/projects/backend-api.png",
    github: "#",
    live: "#",
    category: "backend",
  },
  {
    name: "Auth System",
    description: "Secure user authentication backend.",
    tech: ["JWT", "Express", "MongoDB"],
    image: "/projects/auth.png",
    github: "#",
    live: "#",
    category: "backend",
  },
  {
    name: "Blog API",
    description: "Blog backend with CRUD operations.",
    tech: ["Node.js", "MongoDB"],
    image: "/projects/blog.png",
    github: "#",
    live: "#",
    category: "backend",
  },
  {
    name: "File Upload API",
    description: "Upload & manage files with multer.",
    tech: ["Node.js", "Express"],
    image: "/projects/upload.png",
    github: "#",
    live: "#",
    category: "backend",
  },
  {
    name: "Feedback System",
    description: "Feedback capture and analysis backend.",
    tech: ["Express", "MongoDB"],
    image: "/projects/feedback.png",
    github: "#",
    live: "#",
    category: "backend",
  },

  // Fullstack Projects
  {
    name: "Doctor Appointment System",
    description: "A Full stack doctor appointment system app to book doctor appointments with smart health features.",
    tech: ["React", "Node.js", "MongoDB", "Tailwind"],
    image: img3,
    github: "#",
    live: "https://medicare-frontend123.vercel.app/",
    category: "fullstack",
  },
  {
    name: "Doctor App",
    description: "Book appointments and manage slots.",
    tech: ["React", "Node.js", "MongoDB"],
    image: "/projects/doctor-app.png",
    github: "#",
    live: "#",
    category: "fullstack",
  },
  {
    name: "Doctor App",
    description: "Book appointments and manage slots.",
    tech: ["React", "Node.js", "MongoDB"],
    image: "/projects/doctor-app.png",
    github: "#",
    live: "#",
    category: "fullstack",
  },
  {
    name: "E-Commerce",
    description: "Full-featured shopping site.",
    tech: ["MERN Stack"],
    image: "/projects/ecom.png",
    github: "#",
    live: "#",
    category: "fullstack",
  },
  {
    name: "Blog Platform",
    description: "Write and share your thoughts.",
    tech: ["React", "Express", "MongoDB"],
    image: "/projects/blog-full.png",
    github: "#",
    live: "#",
    category: "fullstack",
  },
  {
    name: "NoteKeeper",
    description: "Secure notes with auth.",
    tech: ["React", "Node.js", "MongoDB"],
    image: "/projects/notes.png",
    github: "#",
    live: "#",
    category: "fullstack",
  },
  {
    name: "Course Platform",
    description: "Sell and manage courses.",
    tech: ["MERN", "JWT"],
    image: "/projects/course.png",
    github: "#",
    live: "#",
    category: "fullstack",
  },

  // Machine Learning Projects
  {
    name: "AI Job Interview",
    description: "Real-time job interviews using AI.",
    tech: ["OpenAI", "WebRTC", "MERN"],
    image: "/projects/ai-interview.png",
    github: "#",
    live: "#",
    category: "machinelearning",
  },
  {
    name: "ML Chatbot",
    description: "Smart chatbot using NLP.",
    tech: ["Python", "Flask", "NLTK"],
    image: "/projects/chatbot.png",
    github: "#",
    live: "#",
    category: "machinelearning",
  },
  {
    name: "Handwriting Detection",
    description: "Detect handwriting using CNN.",
    tech: ["TensorFlow", "Python"],
    image: "/projects/handwriting.png",
    github: "#",
    live: "#",
    category: "machinelearning",
  },
  {
    name: "Fake News Classifier",
    description: "ML model to detect fake news.",
    tech: ["Python", "Scikit-Learn"],
    image: "/projects/fake-news.png",
    github: "#",
    live: "#",
    category: "machinelearning",
  },
  {
    name: "Stock Price Predictor",
    description: "Predict stock prices with LSTM.",
    tech: ["Python", "Keras", "Pandas"],
    image: "/projects/stock.png",
    github: "#",
    live: "#",
    category: "machinelearning",
  },
  {
    name: "Stock Price Predictor",
    description: "Predict stock prices with LSTM.",
    tech: ["Python", "Keras", "Pandas"],
    image: "/projects/stock.png",
    github: "#",
    live: "#",
    category: "machinelearning",
  }
];

export default allProjects;
